# Generated by Django 2.2 on 2022-06-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220316_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
